project_name: Mask2Former Aerial Segmentation

data:
  raw_dir: SS_data
  flair:
    image_dir:
    mask_dir:
  dlr:
    image_dir:
    mask_dir:
  batch_size: 12
  num_classes: 6
  patch_size: 128
  train_split: 0.8
  debug : true
  debug_limit: 300

model:
  name: "Mask2Former"
  pretrained_weights: "facebook/mask2former-swin-small-ade-semantic"
  num_classes: 19
  normalize: true
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  dataset_name: flair
  label_type: dense
  classes_names:
    flair :
      - building
      - pervious surface
      - impervious surface
      - bare soil
      - water
      - coniferous
      - deciduous
      - brushwood
      - vineyard
      - herbaceous vegetation
      - agricultural land
      - plowed land
      - swimming_pool
      - snow
      - clear cut
      - mixed
      - ligneous
      - greenhouse
      - other
    dlr :
      dense :
        - Low vegetation
        - Paved road
        - Non paved road
        - Paved parking place
        - Bikeways
        - Sidewalks
        - Entrance exit
        - Danger area
        - Lane-markings
        - Buildings
        - Car
        - Truck
        - Long Truck
        - Bus
        - Clutter
        - Impervious surface
        - Tree
      multi_lane:
        - Background
        - Dash Line
        - Long Line
        - Small dash line
        - Turn signs
        - Plus sign on crossroads
        - Crosswalk
        - Stop Line
        - Zebra zone
        - No parking zone
        - Parking space
        - Other lane-markings


  learning_rate: 2e-4
  epochs: 25
  freeze_backbone: false
  save_best_only: true
  checkpoint_interval: 5

augmentation:
  horizontal_flip: 0.0
  vertical_flip: 0.0
  rotate_90: 0.5
  brightness_contrast: 0.0
  gaussian_blur: 0.0
  resized_crop:
    enable: false
    height: 128
    width: 128
    scale: [ 0.5, 0.8]
    p: 0.3


training:
  optimizer: AdamW
  loss_function: cross_entropy
  device: cuda
  amp: true
  gradient_clipping: 1.0
  early_stopping: true
  early_stopping_patience: 5

paths:
  base_output_dir: outputs
  run_name: 20240604_mask2former_kaggle
  logs_subdir: logs
  tensorboard_subdir: tensorboard
  checkpoint_subdir: checkpoints
  visualization_subdir: visualizations
  test_results_subdir: test_results


visualization:
  show_masks: true
  save_plots: true
  plot_frequency: 1

logging:
  log_level: info
  log_to_file: true
  log_file: logs/training.log

testing:
  test_batch_size: 2
  test_results_dir: old_outputs/test_results
  evaluation_metrics: [mIoU, accuracy, precision, recall]
