project_name: Mask2Former Aerial Segmentation

data:
  raw_dir: SS_data
  images_dir: /home/ryqc/PycharmProjects/SS_BEV/SS_data/images
  masks_dir: /home/ryqc/PycharmProjects/SS_BEV/SS_data/masks
  processed_dir: data/processed
  batch_size: 12
  num_classes: 6
  patch_size: 256
  train_split: 0.8
  debug : true
  debug_limit: 100

model:
  name: "Mask2Former"
  pretrained_weights: "facebook/mask2former-swin-small-ade-semantic"
  learning_rate: 1e-4
  epochs: 20
  freeze_backbone: false
  save_best_only: true
  checkpoint_interval: 5

augmentation:
  horizontal_flip: 0.0
  vertical_flip: 0.0
  rotate_90: 0.5
  brightness_contrast: 0.0
  gaussian_blur: 0.0
  resized_crop:
    enable: false
    height: 128
    width: 128
    scale: [ 0.5, 0.8]
    p: 0.3


training:
  optimizer: AdamW
  loss_function: cross_entropy
  device: cuda
  amp: true
  gradient_clipping: 1.0
  early_stopping: true
  early_stopping_patience: 5

paths:
  base_output_dir: outputs
  run_name: 20240604_mask2former_kaggle
  logs_subdir: logs
  tensorboard_subdir: tensorboard
  checkpoint_subdir: checkpoints
  visualization_subdir: visualizations
  test_results_subdir: test_results


visualization:
  show_masks: true
  save_plots: true
  plot_frequency: 1

logging:
  log_level: info
  log_to_file: true
  log_file: logs/training.log

testing:
  test_batch_size: 2
  test_results_dir: old_outputs/test_results
  evaluation_metrics: [mIoU, accuracy, precision, recall]
