project_name: Mask2Former Aerial Segmentation

data:
  # Root directories
  raw_dir: SS_data
  images_dir: SS_data/images
  masks_dir: SS_data/masks
  processed_dir: data/processed
  batch_size: 8
  num_classes: 6
  patch_size: 256
  train_split: 0.8

model:
  name: "Mask2Former"
  pretrained_weights: "facebook/mask2former-swin-small-ade-semantic"
  learning_rate: 1e-4
  epochs: 10
  freeze_backbone: true
  save_best_only: true
  checkpoint_interval: 5

training:
  optimizer: AdamW
  loss_function: cross_entropy
  device: cuda

paths:
  output_dir: outputs
  model_save_dir: outputs/models
  visualization_dir: outputs/visualizations
  logs_dir: logs
  checkpoint_path: outputs/models/checkpoints
  best_model_path: outputs/models/best_model.pth

visualization:
  show_masks: true
  save_plots: true
  plot_frequency: 1

logging:
  log_level: info
  log_to_file: true
  log_file: logs/training.log

testing:
  test_batch_size: 8
  test_results_dir: outputs/test_results
  evaluation_metrics: [mIoU, accuracy, precision, recall]
